matrix:
  services:
    postgresql
  include:
    - language: ruby
      rvm:
        - 2.4
      before_script:
       - make setup-movie-api && cp ./movie-api/config/database.yml.travis ./movie-api/config/database.yml
      script: make movie-api

    - language: node_js
      node_is:
        - 9.4
      before_script: make setup-web-client
      script: make web-client
