version: '3.7'

x-common-args-dev: &common-args-dev
  build:
    context: .
    dockerfile: Dockerfile.dev
  volumes:
    - "./movie-api:/opt/movie-api"
    - "./.tmp/movie-api/bundle:/usr/local/bundle"
  working_dir: /opt/movie-api

services:
  ruby:
    <<: *common-args-dev

  gem:
    <<: *common-args-dev
    entrypoint: gem

  bundle:
    <<: *common-args-dev
    entrypoint: bundle
    command: install

  rails:
    <<: *common-args-dev
    entrypoint: rails
    environment:
      DEV_DB_PASSWORD: ${ROOT_DB_PASSWORD}
      TEST_DB_PASSWORD: ${ROOT_DB_PASSWORD}

  rake:
    <<: *common-args-dev
    entrypoint: bin/rake
    environment:
      DEV_DB_PASSWORD: ${ROOT_DB_PASSWORD}
      TEST_DB_PASSWORD: ${ROOT_DB_PASSWORD}

  test:
    <<: *common-args-dev
    entrypoint: bin/rake
    depends_on:
      - db
    command: test
    environment:
      DEV_DB_PASSWORD: ${ROOT_DB_PASSWORD}
      TEST_DB_PASSWORD: ${ROOT_DB_PASSWORD}

  serve:
    <<: *common-args-dev
    entrypoint: bin/rails
    command: server --binding=0.0.0.0
    environment:
      DEV_DB_PASSWORD: ${ROOT_DB_PASSWORD}
      TEST_DB_PASSWORD: ${ROOT_DB_PASSWORD}
    ports:
      - "3000:3000"

  debug:
    <<: *common-args-dev
    entrypoint: rdebug-ide
    command: --host 0.0.0.0 --port 2353 -- bin/rails server --binding=0.0.0.0
    ports:
      - "3000:3000"
      - "2353:2353"

  db:
    hostname: db
    image: postgres:13.3-buster
    environment:
      POSTGRES_USER: movie_api
      POSTGRES_PASSWORD: ${ROOT_DB_PASSWORD}
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - 8898:5432
