Vagrant.configure(2) do |config|

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 2
  end

  config.vm.define "dev" do |dev|
    dev.vm.hostname = "track-my-vids-dev.lan"
    dev.vm.box = "ubuntu/trusty64"
    dev.vm.network"private_network", type: "dhcp"
    dev.vm.synced_folder "../", "/home/vagrant/track-my-vids", create: false
    dev.vm.provision "docker" do |docker|
      docker.run "postgres"
    end
    dev.vm.provision "shell", path: "scripts/install-ruby.sh", privileged: false
    dev.vm.provision "shell", path: "scripts/install-node.sh", privileged: false
  end
end
