Vagrant.configure(2) do |config|

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 2
  end

  config.vm.define "dev" do |dev|
    dev.vm.hostname = "movie-manager-dev.lan"
    dev.vm.box = "ubuntu/trusty64"
    dev.vm.network"private_network", type: "dhcp"
    dev.vm.synced_folder "../", "/home/vagrant/daniel-movie-manager", create: false
    dev.vm.provision "docker" do |docker|
      docker.run "movie-api-dev",
                 image: "postgres",
                 args: "-p 5432:5432 -e POSTGRES_PASSWORD=vagrant -e POSTGRES_USER=movie-api-dev"
      docker.run "movie-api-test",
                 image: "postgres",
                 args: "-p 5433:5432 -e POSTGRES_PASSWORD=vagrant -e POSTGRES_USER=movie-api-test"
    end
    dev.vm.provision "shell", path: "scripts/install-ruby.sh", privileged: false
    dev.vm.provision "shell", path: "scripts/install-node.sh", privileged: false
  end
end
