Vagrant.configure(2) do |config|

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 2
  end

  config.vm.define "dev" do |dev|
    dev.vm.hostname = "movie-manager-dev.lan"
    dev.vm.box = "ubuntu/trusty64"
    dev.vm.network"private_network", ip: "192.168.8.1"
    dev.vm.synced_folder "../", "/home/vagrant/daniel-movie-manager", create: false
    dev.vm.provision "docker" do |docker|
      docker.run "postgres-dev",
                 image: "postgres",
                 args: "-p 5433:5432 -e POSTGRES_PASSWORD=vagrant -e POSTGRES_USER=movie-api-dev"
      docker.run "postgres-test",
                 image: "postgres",
                 args: "-p 5434:5432 -e POSTGRES_PASSWORD=vagrant -e POSTGRES_USER=movie-api-test"
      docker.run "postgres-prod",
                 image: "postgres",
                 args: "-p 5432:5432 -e POSTGRES_PASSWORD=vagrant -e POSTGRES_USER=movie-api"
    end
    dev.vm.provision "shell", path: "scripts/install-ruby.sh", privileged: false
    dev.vm.provision "shell", path: "scripts/install-node.sh", privileged: false
  end

  config.vm.define "int" do |dev|
    dev.vm.hostname = "movie-manager-int.lan"
    dev.vm.box = "ubuntu/trusty64"
    dev.vm.network "private_network", ip: "192.168.8.2"
    dev.vm.provision "docker" do |docker|
      docker.run "postgres",
                 image: "postgres",
                 args: "-p 5432:5432 -e POSTGRES_PASSWORD=vagrant -e POSTGRES_USER=movie-api"
      docker.run "movie-api",
                 image: "lightswitch05/movie-api:0.0.1",
                 args: "-p 3000:3000 -e DATABASE_HOST=$(ifconfig docker0 | grep \"inet \" | awk '{print $2}' | cut -d ':' -f 2) -e DATABASE_PASSWORD=vagrant -e SECRET_KEY_BASE=c91aade7caee5a3116ea2d8d4db7a490c14550eb95f9070416d08f761e6f57c51448169e3442126dbc2c528b06638d7df3159e2e6b81e6ad08bc30aa728ee0b7"
    end
  end
end
