name: Tests

on:
  push:
    branches:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/cache@v2
        with:
          path: |
            ~/.tmp/movie-api/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-

      - name: Install dependencies
        run: docker-compose run --rm bundle install

      - name: Run Tests
        run: |
          docker-compose up -d db
          sleep 10
          docker-compose run --rm rails test
